"""Modificación de tabla Access_log

Revision ID: 1edf3498e79f
Revises: d646c3e28b84
Create Date: 2026-02-22 12:13:04.148658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1edf3498e79f'
down_revision: Union[str, Sequence[str], None] = 'd646c3e28b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_log', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('access_log', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('access_log', 'timestamp')
    op.drop_column('access_log', 'action_type')
    op.drop_column('access_log', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_log', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('access_log', sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('access_log', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('access_log', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('access_log', 'last_login')
    # ### end Alembic commands ###
